export const CHANGE_TOGGLE_STATE = "CHANGE_TOGGLE_STATE";
export const NEW_CLIENT_FORM = "NEW_CLIENT_FORM";
export const ADD_NEW_CLIENT = "ADD_NEW_CLIENT";
export const NEW_VEHICLE_FORM = 'NEW_VEHICLE_FORM';
export const NEW_VEHICLE_TOGGLE = 'NEW_VEHICLE_TOGGLE'